[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  # Include translation files in the function bundle
  included_files = ["packages/server/translations/**/*"]
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/server/api/:splat"

[[redirects]]
  force = true
  from = "/sdk/*"
  status = 200
  to = "/.netlify/functions/server/sdk/:splat"