import {
    ENCRYPTED_CARD_NUMBER,
    ENCRYPTED_EXPIRY_DATE,
    ENCRYPTED_SECURITY_CODE,
    ENCRYPTED_PWD_FIELD
} from '../../../internal/SecuredFields/lib/configuration/constants';

const TAX_NUMBER = 'taxNumber';
const HOLDER_NAME = 'holderName';

export const CREDIT_CARD = [ENCRYPTED_CARD_NUMBER, ENCRYPTED_EXPIRY_DATE, ENCRYPTED_SECURITY_CODE];

export const CREDIT_CARD_NAME_TOP = [HOLDER_NAME, ENCRYPTED_CARD_NUMBER, ENCRYPTED_EXPIRY_DATE, ENCRYPTED_SECURITY_CODE];

export const CREDIT_CARD_NAME_BOTTOM = [ENCRYPTED_CARD_NUMBER, ENCRYPTED_EXPIRY_DATE, ENCRYPTED_SECURITY_CODE, HOLDER_NAME];

export const KCP_CARD = [ENCRYPTED_CARD_NUMBER, ENCRYPTED_EXPIRY_DATE, ENCRYPTED_SECURITY_CODE, TAX_NUMBER, ENCRYPTED_PWD_FIELD];

export const KCP_CARD_NAME_TOP = [
    HOLDER_NAME,
    ENCRYPTED_CARD_NUMBER,
    ENCRYPTED_EXPIRY_DATE,
    ENCRYPTED_SECURITY_CODE,
    TAX_NUMBER,
    ENCRYPTED_PWD_FIELD
];

export const KCP_CARD_NAME_BOTTOM = [
    ENCRYPTED_CARD_NUMBER,
    ENCRYPTED_EXPIRY_DATE,
    ENCRYPTED_SECURITY_CODE,
    HOLDER_NAME,
    TAX_NUMBER,
    ENCRYPTED_PWD_FIELD
];
