import {
    ENCRYPTED_BANK_ACCNT_NUMBER_FIELD,
    ENCRYPTED_BANK_LOCATION_FIELD,
    ENCRYPTED_CARD_NUMBER,
    ENCRYPTED_EXPIRY_DATE,
    ENCRYPTED_EXPIRY_MONTH,
    ENCRYPTED_EXPIRY_YEAR,
    ENCRYPTED_PWD_FIELD,
    ENCRYPTED_SECURITY_CODE
} from '../../components/internal/SecuredFields/lib/configuration/constants';

export const ARIA_ERROR_SUFFIX = '-ariaError';
export const ARIA_CONTEXT_SUFFIX = '-ariaContext';

export const ERROR_ACTION_FOCUS_FIELD = 'focusField';
export const ERROR_ACTION_BLUR_SCENARIO = 'notValidating:blurScenario';
export const ERROR_KEY_REQUIRED = 'field.error.required';
export const ERROR_KEY_INVALID = 'field.error.invalid';

/**
 * Map of human readable error strings to the codes, used as keys, in the translations files
 */
export enum ErrorCodes {
    ERROR_MSG_INCOMPLETE_FIELD = 'err-gen-9100',
    ERROR_MSG_INVALID_FIELD = 'err-gen-9101',

    ERROR_MSG_LUHN_CHECK_FAILED = 'cc-num-902',
    ERROR_MSG_EMPTY_PAN = 'cc-num-900',
    ERROR_MSG_UNSUPPORTED_CARD_ENTERED = 'cc-num-903',
    ERROR_MSG_INCORRECTLY_FILLED_PAN = 'cc-num-901', // 'Enter the complete card number'

    ERROR_MSG_CARD_TOO_OLD = 'cc-dat-912',
    ERROR_MSG_CARD_TOO_FAR_IN_FUTURE = 'cc-dat-913',
    ERROR_MSG_CARD_EXPIRES_TOO_SOON = 'cc-dat-914',
    ERROR_MSG_EMPTY_DATE = 'cc-dat-910',
    ERROR_MSG_INCORRECTLY_FILLED__DATE = 'cc-dat-911',

    ERROR_MSG_EMPTY_YEAR = 'cc-yr-917',
    ERROR_MSG_INCORRECTLY_FILLED_YEAR = 'cc-yr-918',

    // ERROR_MSG_INCORRECTLY_FILLED_MONTH= 'cc-mth-916',
    ERROR_MSG_EMPTY_MONTH = 'cc-mth-915',

    ERROR_MSG_EMPTY_CVC = 'cc-cvc-920',
    ERROR_MSG_INCORRECTLY_FILLED_CVC = 'cc-cvc-921',

    ERROR_MSG_EMPTY_KCP_PWD = 'kcp-pwd-940',
    ERROR_MSG_INCORRECTLY_FILLED_KCP_PWD = 'kcp-pwd-941',

    ERROR_MSG_EMPTY_ACH_ACCOUNT_NUMBER = 'ach-num-945',
    ERROR_MSG_INCORRECTLY_FILLED_ACH_ACCOUNT_NUMBER = 'ach-num-946',

    ERROR_MSG_EMPTY_ACH_BANK_LOCATION_ID = 'ach-loc-947',
    ERROR_MSG_INCORRECTLY_FILLED_ACH_BANK_LOCATION_ID = 'ach-loc-948'
}

export const EMPTY_FIELD_ERROR_MESSAGES = {
    [ENCRYPTED_CARD_NUMBER]: ErrorCodes.ERROR_MSG_EMPTY_PAN,
    [ENCRYPTED_EXPIRY_DATE]: ErrorCodes.ERROR_MSG_EMPTY_DATE,
    [ENCRYPTED_EXPIRY_MONTH]: ErrorCodes.ERROR_MSG_EMPTY_MONTH,
    [ENCRYPTED_EXPIRY_YEAR]: ErrorCodes.ERROR_MSG_EMPTY_YEAR,
    [ENCRYPTED_SECURITY_CODE]: ErrorCodes.ERROR_MSG_EMPTY_CVC,
    [ENCRYPTED_PWD_FIELD]: ErrorCodes.ERROR_MSG_EMPTY_KCP_PWD,
    [ENCRYPTED_BANK_ACCNT_NUMBER_FIELD]: ErrorCodes.ERROR_MSG_EMPTY_ACH_ACCOUNT_NUMBER,
    [ENCRYPTED_BANK_LOCATION_FIELD]: ErrorCodes.ERROR_MSG_EMPTY_ACH_BANK_LOCATION_ID
};
