export const DEFAULT_PAYMENT_STATUS_TIMER_DELAY = 2_000;
export const DEFAULT_PAYMENT_STATUS_TIMER_THROTTLE_TIME = 60_000;
export const DEFAULT_PAYMENT_STATUS_TIMER_THROTTLE_INTERVAL = 10_000;
export const DEFAULT_PAYMENT_STATUS_TIMER_COUNTDOWN_TIME = 15;
