name: Size limit

on: [pull_request]

jobs:
  size:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 18.18
        uses: actions/setup-node@v4
        with:
          node-version: 18.18

      - uses: andresz1/size-limit-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: packages/lib
          package_manager: yarn
