name: Size limit

on: [pull_request]

jobs:
  size:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.18.0]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: node-modules-v1
        with:
          path: node_modules
          key: ${{ runner.os }}-cache-${{ env.cache-name }}-node-${{ matrix.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-cache-${{ env.cache-name }}-node-${{ matrix.node-version }}-yarn-

      - name: Enable Corepack
        run: corepack enable

      - uses: andresz1/size-limit-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: packages/lib
          package_manager: yarn
