name: Size limit

on: [pull_request]

jobs:
  size:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Use Node.js 22.18.0
        uses: actions/setup-node@v5
        with:
          node-version: 22.18.0

      - name: Enable Corepack
        run: corepack enable

      - uses: andresz1/size-limit-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: packages/lib
          package_manager: yarn
