name: Manual Approval

on:
  push:
    branches: [ feature/manual-approval-poc ]
  workflow_dispatch:

jobs:
    log-one:
      runs-on: ubuntu-latest
      steps:
          - name: Log first message
            run: echo "Hello from first job"

    manual-approval:
      needs: log-one
      runs-on: ubuntu-latest
      environment: test-manual-approval
      continue-on-error: true
      outputs:
        approved: ${{ steps.gate.outputs.approved }}
      steps:
        - id: gate
          name: Manual approval gate
          run: |
            echo "approved=true" >> $GITHUB_OUTPUT
    
    log-two:
      needs: manual-approval
      if: ${{ needs.manual-approval.outputs.approved == 'true' }}
      runs-on: ubuntu-latest
      steps:
        - name: Log second message
          run: echo "Hello from second job"
