name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v7
      with:
        node-version: 24
        package-manager-cache: false

    - name: Cache node modules
      id: node-modules-cache
      uses: actions/cache@v6
      env:
        cache-name: node-modules-v1
      with:
        path: node_modules
        key: ${{ runner.os }}-cache-${{ env.cache-name }}-yarn-${{ hashFiles('**/yarn.lock') }}

    - name: Enable Corepack
      run: corepack enable

    - name: Install Project Dependencies
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      run: yarn install --immutable

    - name: Generate test coverage
      run: yarn test:coverage

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8.2.1
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
