name: SonarQube analysis (SonarCloud)

# use SonarCloud action has been deprecated and now we should use SonarCube action
# Old https://github.com/SonarSource/sonarcloud-github-action?tab=readme-ov-file
# New https://github.com/marketplace/actions/official-sonarqube-scan

on:
  push:
  pull_request:
  merge_group:
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Analyze with SonarCube

        # You can pin the exact commit or the version.
        # uses: SonarSource/sonarcloud-github-action@v2.2.0
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
