name: Github Stale Issues Check

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight

jobs:
  close_stale_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale issues
        uses: actions/stale@v9
        with:
          any-of-labels: 'Needs more info'
          stale-issue-message: 'This issue is stale because it has been open 21 days with no activity. Please comment on this issue otherwise it will be closed in 7 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity.'
          days-before-issue-stale: 21
          days-before-issue-close: 7
