name: Validate remote assets

on:
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main

jobs:
  check-secured-fields-assets:
    if: contains(github.head_ref, 'changeset-release')

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Getting SF_VERSION in the codebase
        run: |
          echo "SF_VERSION=$(grep -e 'SF_VERSION' packages/lib/src/components/internal/SecuredFields/lib/constants.ts | cut -d "'" -f2)" >> $GITHUB_ENV

      - name: Encoding test origin URL to base64
        env:
          TEST_ORIGIN: ${{ secrets.TEST_ORIGIN }}
        run: |
          BTOA=$(printf "%s" "$TEST_ORIGIN" | base64 -w 0)
          echo "::add-mask::$BTOA"
          echo "BTOA_TEST_ORIGIN=$BTOA" >> $GITHUB_ENV

      - name: Requesting securedFields in production
        id: securedFieldsRequest
        env:
          TEST_CLIENT_KEY: ${{ secrets.TEST_CLIENT_KEY }}
          TEST_ORIGIN: ${{ secrets.TEST_ORIGIN }}
        run: |
          curl -fsS -o /dev/null \
            -H "Origin: ${TEST_ORIGIN}" \
            "https://checkoutshopper-live-us.adyen.com/checkoutshopper/securedfields/${TEST_CLIENT_KEY}/${SF_VERSION}/securedFields.html?type=card&d=${BTOA_TEST_ORIGIN}"

      - name: Comment PR that request failed
        if: failure()
        uses: actions/github-script@v9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            await github.rest.issues.createComment({ issue_number, owner, repo, body: '⚠️ WARNING: SecuredFields v${{ env.SF_VERSION }} might not be available live ⚠️' });


      - name: Comment PR that request succeeded
        if: success()
        uses: actions/github-script@v9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            await github.rest.issues.createComment({ issue_number, owner, repo, body: '✅ SecuredFields v${{ env.SF_VERSION }} are available live' });
